spring:
  application:
    name:
      CoveredV2
  security:
    user:
      name: user
      password: password
      roles: PROMETHEUS
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:file:./data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
management:
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health,readiness,liveness,prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      access: unrestricted
app:
  response-timeout: 1
  steam:
    api-key: ${STEAM_API_KEY}
  steamgriddb:
    api-key: ${STREAMGRIDDB_API_KEY}
    concurrency_count: 50
server:
  error:
    include-message: always