spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: {DATABASE_URL}
    username: {DATABASE_USERNAME}
    password: {DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver